name: SKY UX CI

on:
  pull_request:
    branches:
      - 7.x.x
  push:
    branches:
      - 7.x.x
    tags:
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.x'
      - uses: blackbaud/skyux-sdk-actions@ng-14
        with:
          browser-stack-access-key: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          browser-stack-username: ${{ secrets.BROWSER_STACK_USERNAME }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          project: help
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          code-coverage-browser-set: speedy
          code-coverage-threshold-branches: 96
          code-coverage-threshold-functions: 100
          code-coverage-threshold-lines: 98
          code-coverage-threshold-statements: 98
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
